import { Form } from "../fieldTypes";

export const FORM_DATA: Form = {
  collections: [
    {
      fieldIdentifiers: [
        "minor_full_name",
        "minor_birthday",
        "minor_relation_to_user",
      ],
      maxCount: 4,
      title: "Add Minors",
    },
  ],
  fields: {
    date: {
      coordinates: [
        { coordinate: [363, 50], page: 1 },
        { coordinate: [38, 270], page: 3 },
        { coordinate: [38, 200], page: 3 },
        { coordinate: [395, 679], page: 4 },
        { coordinate: [469, 155], page: 7 },
        { coordinate: [469, 99], page: 7 },
        { coordinate: [411, 130], page: 8 },
        { coordinate: [380, 529], page: 9 },
        { coordinate: [448, 489], page: 9 },
        { coordinate: [363, 512], page: 11 },
      ],
      default: [new Date().toLocaleDateString()],
      renderFieldInPDF: false,
    },
    owner_full_name: {
      coordinates: [{ coordinate: [115, 260], page: 3 }],
      default: ["Rayvon Solomon"],
      renderFieldInPDF: false,
    },
    owner_signature: {
      coordinates: [
        { coordinate: [335, 260], page: 3 },
        { coordinate: [135, 155], page: 7 },
      ],
      default: ["Rayvon Solomon"],
      renderFieldInPDF: false,
    },
    first_name: {
      coordinates: [],
      inputType: "text",
      renderFieldInPDF: true,
      minCount: 1,
      maxCount: 1,
    },
    last_name: {
      coordinates: [],
      inputType: "text",
      renderFieldInPDF: true,
      minCount: 1,
      maxCount: 1,
    },
    full_name: {
      coordinates: [
        { coordinate: [115, 185], page: 3 },
        { coordinate: [168, 638], page: 4 },
        { coordinate: [92, 225], page: 8 },
        { coordinate: [39, 258], page: 10 },
        { coordinate: [221, 614], page: 11 },
      ],
      renderFieldInPDF: false,
      default: ["first_name", "last_name"],
      separator: " ",
    },
    age: {
      coordinates: [{ coordinate: [463, 638], page: 4 }],
      inputType: "number",
      renderFieldInPDF: true,
      minCount: 1,
      maxCount: 1,
    },
    location: {
      coordinates: [{ coordinate: [78, 420], page: 5 }],
      inputType: "text",
      renderFieldInPDF: true,
      minCount: 1,
      maxCount: 1,
      hasValues: [
        "Bayview Park",
        "Caxambas Park",
        "Cocohatchee River Park",
        "Collier Blvd Boating Park",
        "Goodland Boating Park",
        "Port Of Isles Marina",
      ],
    },
    owner_initials: {
      coordinates: [
        { coordinate: [78, 660], page: 2 },
        { coordinate: [78, 615], page: 2 },
        { coordinate: [78, 575], page: 2 },
        { coordinate: [78, 537], page: 2 },
        { coordinate: [78, 500], page: 2 },
        { coordinate: [78, 465], page: 2 },
        { coordinate: [78, 425], page: 2 },
        { coordinate: [78, 390], page: 2 },
        { coordinate: [78, 355], page: 2 },
        { coordinate: [78, 320], page: 2 },
        { coordinate: [78, 283], page: 2 },
        { coordinate: [78, 245], page: 2 },
        { coordinate: [78, 210], page: 2 },
        { coordinate: [78, 173], page: 2 },
        { coordinate: [78, 137], page: 2 },
        { coordinate: [78, 690], page: 3 },
        { coordinate: [78, 650], page: 3 },
        { coordinate: [78, 615], page: 3 },
        { coordinate: [78, 580], page: 3 },
        { coordinate: [78, 542], page: 3 },
        { coordinate: [78, 505], page: 3 },
        { coordinate: [78, 450], page: 3 },
        { coordinate: [78, 400], page: 3 },
        { coordinate: [78, 350], page: 3 },
        { coordinate: [78, 316], page: 3 },
      ],
      default: ["R.S."],
      renderFieldInPDF: false,
    },
    initials: {
      callbackKey: "getInitialsOfFullName",
      coordinates: [
        { coordinate: [38, 660], page: 2 },
        { coordinate: [38, 615], page: 2 },
        { coordinate: [38, 575], page: 2 },
        { coordinate: [38, 537], page: 2 },
        { coordinate: [38, 500], page: 2 },
        { coordinate: [38, 465], page: 2 },
        { coordinate: [38, 425], page: 2 },
        { coordinate: [38, 390], page: 2 },
        { coordinate: [38, 355], page: 2 },
        { coordinate: [38, 320], page: 2 },
        { coordinate: [38, 283], page: 2 },
        { coordinate: [38, 245], page: 2 },
        { coordinate: [38, 210], page: 2 },
        { coordinate: [38, 173], page: 2 },
        { coordinate: [38, 137], page: 2 },
        { coordinate: [38, 690], page: 3 },
        { coordinate: [38, 650], page: 3 },
        { coordinate: [38, 615], page: 3 },
        { coordinate: [38, 580], page: 3 },
        { coordinate: [38, 542], page: 3 },
        { coordinate: [38, 505], page: 3 },
        { coordinate: [38, 450], page: 3 },
        { coordinate: [38, 400], page: 3 },
        { coordinate: [38, 350], page: 3 },
        { coordinate: [38, 316], page: 3 },
      ],
      default: ["first_name", "last_name"],
      renderFieldInPDF: false,
    },
    signature: {
      coordinates: [
        { coordinate: [62, 50], page: 1 },
        { coordinate: [335, 185], page: 3 },
        { coordinate: [135, 99], page: 7 },
        { coordinate: [134, 130], page: 8 },
        { coordinate: [38, 529], page: 9 },
        { coordinate: [38, 489], page: 9 },
        { coordinate: [92, 512], page: 11 },
      ],
      default: ["full_name"],
      renderFieldInPDF: false,
    },
    date_of_birth: {
      coordinates: [
        { coordinate: [345, 225], page: 8 },
        { coordinate: [352, 537], page: 11 },
      ],
      inputType: "date",
      renderFieldInPDF: true,
      minCount: 1,
      maxCount: 1,
    },
    phone_number: {
      coordinates: [
        { coordinate: [473, 225], page: 8 },
        { coordinate: [123, 537], page: 11 },
      ],
      inputType: "tel",
      renderFieldInPDF: true,
      minCount: 1,
      maxCount: 1,
    },
    address: {
      coordinates: [
        { coordinate: [77, 193], page: 8 },
        { coordinate: [82, 588], page: 11 },
      ],
      inputType: "text",
      renderFieldInPDF: true,
      minCount: 1,
      maxCount: 1,
    },
    city: {
      coordinates: [
        { coordinate: [383, 193], page: 8 },
        { coordinate: [61, 563], page: 11 },
      ],
      inputType: "text",
      renderFieldInPDF: true,
      minCount: 1,
      maxCount: 1,
    },
    state: {
      coordinates: [
        { coordinate: [62, 162], page: 8 },
        { coordinate: [264, 563], page: 11 },
      ],
      inputType: "text",
      renderFieldInPDF: true,
      hasValues: [
        "Alabama",
        "Alaska",
        "Arizona",
        "Arkansas",
        "California",
        "Colorado",
        "Connecticut",
        "Delaware",
        "District of Columbia",
        "Florida",
        "Georgia",
        "Hawaii",
        "Idaho",
        "Illinois",
        "Indiana",
        "Iowa",
        "Kansas",
        "Kentucky",
        "Louisiana",
        "Maine",
        "Montana",
        "Nebraska",
        "Nevada",
        "New Hampshire",
        "New Jersey",
        "New Mexico",
        "New York",
        "North Carolina",
        "North Dakota",
        "Ohio",
        "Oklahoma",
        "Oregon",
        "Maryland",
        "Massachusetts",
        "Michigan",
        "Minnesota",
        "Mississippi",
        "Missouri",
        "Pennsylvania",
        "Rhode Island",
        "South Carolina",
        "South Dakota",
        "Tennessee",
        "Texas",
        "Utah",
        "Vermont",
        "Virginia",
        "Washington",
        "West Virginia",
        "Wisconsin",
        "Wyoming",
      ],
      minCount: 1,
      maxCount: 1,
    },
    zip: {
      coordinates: [
        { coordinate: [202, 162], page: 8 },
        { coordinate: [345, 563], page: 11 },
      ],
      inputType: "number",
      renderFieldInPDF: true,
      minCount: 1,
      maxCount: 1,
    },
    email: {
      coordinates: [{ coordinate: [319, 162], page: 8 }],
      inputType: "email",
      renderFieldInPDF: true,
      minCount: 1,
      maxCount: 1,
    },
    concat_all_full_names_of_minors: {
      coordinates: [{ coordinate: [264, 489], page: 9 }],
      default: ["minor_full_name"],
      renderFieldInPDF: false,
    },

    // // First minor choice
    minor_full_name: {
      coordinates: [
        { coordinate: [120, 462], page: 11 },
        { coordinate: [120, 428], page: 11 },
        { coordinate: [120, 392], page: 11 },
        { coordinate: [120, 356], page: 11 },
      ],
      minCount: 1,
      renderFieldInPDF: true,
      inputType: "text",
    },
    minor_birthday: {
      coordinates: [
        { coordinate: [338, 462], page: 11 },
        { coordinate: [338, 428], page: 11 },
        { coordinate: [338, 392], page: 11 },
        { coordinate: [338, 356], page: 11 },
      ],
      minCount: 1,
      renderFieldInPDF: true,
      inputType: "date",
    },
    minor_relation_to_user: {
      coordinates: [
        { coordinate: [465, 462], page: 11 },
        { coordinate: [465, 428], page: 11 },
        { coordinate: [465, 392], page: 11 },
        { coordinate: [465, 356], page: 11 },
      ],
      minCount: 1,
      renderFieldInPDF: true,
      inputType: "text",
    },
  },
  title: "Rental Agreement",
};
